[package]
name = "delaunay"
version = "0.1.0"
authors = ["LeshaInc <includeurl@gmail.com>"]
edition = "2018"

[dependencies]
ordered-float = { version = "1.0", features = ["serde"]}
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.6"
