[package]
name = "wasm-demo"
version = "0.1.0"
authors = ["LeshaInc <includeurl@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.triangulation]
path = "../"

[profile.release]
opt-level = "s"
